# Generated by Django 4.2.29 on 2026-04-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_fcm_token'),
        ('accounts', '0002_usersettings'),
    ]

    operations = [
    ]
