# Generated by Django 4.2.29 on 2026-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='game_level',
            field=models.CharField(blank=True, choices=[('Новичок', 'Новичок'), ('Любитель', 'Любитель'), ('Профи', 'Профи')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('Вратарь', 'Вратарь'), ('Защитник', 'Защитник'), ('Полузащитник', 'Полузащитник'), ('Нападающий', 'Нападающий')], default='', max_length=20),
        ),
    ]
