# Generated by Django 5.2.7 on 2026-03-26 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('venues', '0002_venue_closes_at_venue_opens_at_venue_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='venues.venue'),
        ),
    ]
