# Generated by Django 6.0.3 on 2026-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('sport', models.CharField(choices=[('football', 'Футбол'), ('basketball', 'Баскетбол'), ('volleyball', 'Волейбол'), ('tennis', 'Теннис'), ('swimming', 'Плавание'), ('other', 'Другое')], max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
