# Generated by Django 5.2.7 on 2026-03-26 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='closes_at',
            field=models.TimeField(default='23:00'),
        ),
        migrations.AddField(
            model_name='venue',
            name='opens_at',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_venues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venue',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
