# Generated by Django 4.2.29 on 2026-04-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_review'),
        ('venues', '0003_timeslot'),
    ]

    operations = [
    ]
